# Generated by Django 5.1 on 2024-09-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orga_structure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orga_structure",
            name="parentId",
            field=models.IntegerField(null=True),
        ),
    ]
